/*
 * MITA Notifications Platform REST API
 *
 * The Notifications REST API allows programmatic access to the Notifications Portal message funtionality. To use the REST API, you will need a Notifications Portal Account and an API key and secret. You can generate from the Notifications Portal using the API Key Manager.The REST API takes full advantage of all HTTP headers. Each part of a request and response is meaningful, including the request method (GET/POST, etc.), the individual headers (Location, Content-Type, Accept, etc.), and the response status code (200, 400, 404, etc.). Use of this API assumes a working knowledge of these HTTP components, and general use of RESTful web APIs.
 *
 * The version of the OpenAPI document: v1
 * Contact: notifications.mita@gov.mt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Mita.Notifications.Client.Model;
using Mita.Notifications.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Mita.Notifications.Client.Test.Model;

/// <summary>
///  Class for testing MessageReceipt
/// </summary>
/// <remarks>
/// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
/// Please update the test case below to test the model.
/// </remarks>
public class MessageReceiptTests : IDisposable
{
    // TODO uncomment below to declare an instance variable for MessageReceipt
    //private MessageReceipt instance;

    public MessageReceiptTests()
    {
            // TODO uncomment below to create an instance of MessageReceipt
            //instance = new MessageReceipt();
        }

    public void Dispose()
    {
            // Cleanup when everything is done.
        }

    /// <summary>
    /// Test an instance of MessageReceipt
    /// </summary>
    [Fact]
    public void MessageReceiptInstanceTest()
    {
            // TODO uncomment below to test "IsType" MessageReceipt
            //Assert.IsType<MessageReceipt>(instance);
        }

    /// <summary>
    /// Test the property 'Language'
    /// </summary>
    [Fact]
    public void LanguageTest()
    {
            // TODO unit test for the property 'Language'
        }

    /// <summary>
    /// Test the property 'CharacterCount'
    /// </summary>
    [Fact]
    public void CharacterCountTest()
    {
            // TODO unit test for the property 'CharacterCount'
        }

    /// <summary>
    /// Test the property 'MessagePartsCount'
    /// </summary>
    [Fact]
    public void MessagePartsCountTest()
    {
            // TODO unit test for the property 'MessagePartsCount'
        }

    /// <summary>
    /// Test the property 'MessagePartMaxCharacters'
    /// </summary>
    [Fact]
    public void MessagePartMaxCharactersTest()
    {
            // TODO unit test for the property 'MessagePartMaxCharacters'
        }

    /// <summary>
    /// Test the property 'MessageParts'
    /// </summary>
    [Fact]
    public void MessagePartsTest()
    {
            // TODO unit test for the property 'MessageParts'
        }

    /// <summary>
    /// Test the property 'Encoding'
    /// </summary>
    [Fact]
    public void EncodingTest()
    {
            // TODO unit test for the property 'Encoding'
        }

    /// <summary>
    /// Test the property 'LocalMessagePrice'
    /// </summary>
    [Fact]
    public void LocalMessagePriceTest()
    {
            // TODO unit test for the property 'LocalMessagePrice'
        }

    /// <summary>
    /// Test the property 'InternationalMessagePrice'
    /// </summary>
    [Fact]
    public void InternationalMessagePriceTest()
    {
            // TODO unit test for the property 'InternationalMessagePrice'
        }

    /// <summary>
    /// Test the property 'TotalRecipientsCount'
    /// </summary>
    [Fact]
    public void TotalRecipientsCountTest()
    {
            // TODO unit test for the property 'TotalRecipientsCount'
        }

    /// <summary>
    /// Test the property 'TotalMessagesCount'
    /// </summary>
    [Fact]
    public void TotalMessagesCountTest()
    {
            // TODO unit test for the property 'TotalMessagesCount'
        }

    /// <summary>
    /// Test the property 'TotalCost'
    /// </summary>
    [Fact]
    public void TotalCostTest()
    {
            // TODO unit test for the property 'TotalCost'
        }

    /// <summary>
    /// Test the property 'WarningMessages'
    /// </summary>
    [Fact]
    public void WarningMessagesTest()
    {
            // TODO unit test for the property 'WarningMessages'
        }
}