/*
 * Norsk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: helpdesk@norsk-global.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DA.Systems.Cube.Norsk.Model;
using DA.Systems.Cube.Norsk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DA.Systems.Cube.Norsk.Test.Model
{
    /// <summary>
    ///  Class for testing Declarations
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeclarationsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Declarations
        //private Declarations instance;

        public DeclarationsTests()
        {
            // TODO uncomment below to create an instance of Declarations
            //instance = new Declarations();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Declarations
        /// </summary>
        [Fact]
        public void DeclarationsInstanceTest()
        {
            // TODO uncomment below to test "IsType" Declarations
            //Assert.IsType<Declarations>(instance);
        }

        /// <summary>
        /// Test the property 'PreferentialOrigin'
        /// </summary>
        [Fact]
        public void PreferentialOriginTest()
        {
            // TODO unit test for the property 'PreferentialOrigin'
        }

        /// <summary>
        /// Test the property 'TransportationCost'
        /// </summary>
        [Fact]
        public void TransportationCostTest()
        {
            // TODO unit test for the property 'TransportationCost'
        }

        /// <summary>
        /// Test the property 'FreightCost'
        /// </summary>
        [Fact]
        public void FreightCostTest()
        {
            // TODO unit test for the property 'FreightCost'
        }

        /// <summary>
        /// Test the property 'Insurance'
        /// </summary>
        [Fact]
        public void InsuranceTest()
        {
            // TODO unit test for the property 'Insurance'
        }
    }
}
