/*
 * Norsk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: helpdesk@norsk-global.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DA.Systems.Cube.Norsk.Model;
using DA.Systems.Cube.Norsk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DA.Systems.Cube.Norsk.Test.Model
{
    /// <summary>
    ///  Class for testing Dimensions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DimensionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Dimensions
        //private Dimensions instance;

        public DimensionsTests()
        {
            // TODO uncomment below to create an instance of Dimensions
            //instance = new Dimensions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Dimensions
        /// </summary>
        [Fact]
        public void DimensionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" Dimensions
            //Assert.IsType<Dimensions>(instance);
        }

        /// <summary>
        /// Test the property 'NorskBarcode'
        /// </summary>
        [Fact]
        public void NorskBarcodeTest()
        {
            // TODO unit test for the property 'NorskBarcode'
        }

        /// <summary>
        /// Test the property 'Depth'
        /// </summary>
        [Fact]
        public void DepthTest()
        {
            // TODO unit test for the property 'Depth'
        }

        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }

        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }

        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Fact]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }

        /// <summary>
        /// Test the property 'VolumeWeight'
        /// </summary>
        [Fact]
        public void VolumeWeightTest()
        {
            // TODO unit test for the property 'VolumeWeight'
        }

        /// <summary>
        /// Test the property 'ImageUrl'
        /// </summary>
        [Fact]
        public void ImageUrlTest()
        {
            // TODO unit test for the property 'ImageUrl'
        }
    }
}
