/*
 * Norsk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: helpdesk@norsk-global.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DA.Systems.Cube.Norsk.Model;
using DA.Systems.Cube.Norsk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DA.Systems.Cube.Norsk.Test.Model
{
    /// <summary>
    ///  Class for testing ErrorMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ErrorMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ErrorMessage
        //private ErrorMessage instance;

        public ErrorMessageTests()
        {
            // TODO uncomment below to create an instance of ErrorMessage
            //instance = new ErrorMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ErrorMessage
        /// </summary>
        [Fact]
        public void ErrorMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" ErrorMessage
            //Assert.IsType<ErrorMessage>(instance);
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Fact]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
    }
}
