/*
 * Norsk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: helpdesk@norsk-global.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DA.Systems.Cube.Norsk.Model;
using DA.Systems.Cube.Norsk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DA.Systems.Cube.Norsk.Test.Model
{
    /// <summary>
    ///  Class for testing LabelSize
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LabelSizeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LabelSize
        //private LabelSize instance;

        public LabelSizeTests()
        {
            // TODO uncomment below to create an instance of LabelSize
            //instance = new LabelSize();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LabelSize
        /// </summary>
        [Fact]
        public void LabelSizeInstanceTest()
        {
            // TODO uncomment below to test "IsType" LabelSize
            //Assert.IsType<LabelSize>(instance);
        }
    }
}
