/*
 * Norsk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: helpdesk@norsk-global.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DA.Systems.Cube.Norsk.Model;
using DA.Systems.Cube.Norsk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DA.Systems.Cube.Norsk.Test.Model
{
    /// <summary>
    ///  Class for testing LocalTime
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LocalTimeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LocalTime
        //private LocalTime instance;

        public LocalTimeTests()
        {
            // TODO uncomment below to create an instance of LocalTime
            //instance = new LocalTime();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LocalTime
        /// </summary>
        [Fact]
        public void LocalTimeInstanceTest()
        {
            // TODO uncomment below to test "IsType" LocalTime
            //Assert.IsType<LocalTime>(instance);
        }

        /// <summary>
        /// Test the property 'Hour'
        /// </summary>
        [Fact]
        public void HourTest()
        {
            // TODO unit test for the property 'Hour'
        }

        /// <summary>
        /// Test the property 'ClockHourOfHalfDay'
        /// </summary>
        [Fact]
        public void ClockHourOfHalfDayTest()
        {
            // TODO unit test for the property 'ClockHourOfHalfDay'
        }

        /// <summary>
        /// Test the property 'Minute'
        /// </summary>
        [Fact]
        public void MinuteTest()
        {
            // TODO unit test for the property 'Minute'
        }

        /// <summary>
        /// Test the property 'Second'
        /// </summary>
        [Fact]
        public void SecondTest()
        {
            // TODO unit test for the property 'Second'
        }

        /// <summary>
        /// Test the property 'Millisecond'
        /// </summary>
        [Fact]
        public void MillisecondTest()
        {
            // TODO unit test for the property 'Millisecond'
        }

        /// <summary>
        /// Test the property 'TickOfSecond'
        /// </summary>
        [Fact]
        public void TickOfSecondTest()
        {
            // TODO unit test for the property 'TickOfSecond'
        }

        /// <summary>
        /// Test the property 'TickOfDay'
        /// </summary>
        [Fact]
        public void TickOfDayTest()
        {
            // TODO unit test for the property 'TickOfDay'
        }

        /// <summary>
        /// Test the property 'NanosecondOfSecond'
        /// </summary>
        [Fact]
        public void NanosecondOfSecondTest()
        {
            // TODO unit test for the property 'NanosecondOfSecond'
        }

        /// <summary>
        /// Test the property 'NanosecondOfDay'
        /// </summary>
        [Fact]
        public void NanosecondOfDayTest()
        {
            // TODO unit test for the property 'NanosecondOfDay'
        }
    }
}
