/*
 * Norsk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: helpdesk@norsk-global.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DA.Systems.Cube.Norsk.Model;
using DA.Systems.Cube.Norsk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DA.Systems.Cube.Norsk.Test.Model
{
    /// <summary>
    ///  Class for testing Piece
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PieceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Piece
        //private Piece instance;

        public PieceTests()
        {
            // TODO uncomment below to create an instance of Piece
            //instance = new Piece();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Piece
        /// </summary>
        [Fact]
        public void PieceInstanceTest()
        {
            // TODO uncomment below to test "IsType" Piece
            //Assert.IsType<Piece>(instance);
        }

        /// <summary>
        /// Test the property 'Depth'
        /// </summary>
        [Fact]
        public void DepthTest()
        {
            // TODO unit test for the property 'Depth'
        }

        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }

        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }

        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Fact]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }

        /// <summary>
        /// Test the property 'NumberOfPieces'
        /// </summary>
        [Fact]
        public void NumberOfPiecesTest()
        {
            // TODO unit test for the property 'NumberOfPieces'
        }

        /// <summary>
        /// Test the property 'Products'
        /// </summary>
        [Fact]
        public void ProductsTest()
        {
            // TODO unit test for the property 'Products'
        }
    }
}
