/*
 * Norsk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: helpdesk@norsk-global.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DA.Systems.Cube.Norsk.Model;
using DA.Systems.Cube.Norsk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DA.Systems.Cube.Norsk.Test.Model
{
    /// <summary>
    ///  Class for testing Product
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Product
        //private Product instance;

        public ProductTests()
        {
            // TODO uncomment below to create an instance of Product
            //instance = new Product();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Product
        /// </summary>
        [Fact]
        public void ProductInstanceTest()
        {
            // TODO uncomment below to test "IsType" Product
            //Assert.IsType<Product>(instance);
        }

        /// <summary>
        /// Test the property 'ProductDescription'
        /// </summary>
        [Fact]
        public void ProductDescriptionTest()
        {
            // TODO unit test for the property 'ProductDescription'
        }

        /// <summary>
        /// Test the property 'CountryOfManufacture'
        /// </summary>
        [Fact]
        public void CountryOfManufactureTest()
        {
            // TODO unit test for the property 'CountryOfManufacture'
        }

        /// <summary>
        /// Test the property 'HSCode'
        /// </summary>
        [Fact]
        public void HSCodeTest()
        {
            // TODO unit test for the property 'HSCode'
        }

        /// <summary>
        /// Test the property 'ProductUnitValue'
        /// </summary>
        [Fact]
        public void ProductUnitValueTest()
        {
            // TODO unit test for the property 'ProductUnitValue'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'ProductUnitWeight'
        /// </summary>
        [Fact]
        public void ProductUnitWeightTest()
        {
            // TODO unit test for the property 'ProductUnitWeight'
        }

        /// <summary>
        /// Test the property 'ProductQuantity'
        /// </summary>
        [Fact]
        public void ProductQuantityTest()
        {
            // TODO unit test for the property 'ProductQuantity'
        }
    }
}
