/*
 * Norsk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: helpdesk@norsk-global.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DA.Systems.Cube.Norsk.Model;
using DA.Systems.Cube.Norsk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DA.Systems.Cube.Norsk.Test.Model
{
    /// <summary>
    ///  Class for testing QuoteResponseModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QuoteResponseModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QuoteResponseModel
        //private QuoteResponseModel instance;

        public QuoteResponseModelTests()
        {
            // TODO uncomment below to create an instance of QuoteResponseModel
            //instance = new QuoteResponseModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QuoteResponseModel
        /// </summary>
        [Fact]
        public void QuoteResponseModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" QuoteResponseModel
            //Assert.IsType<QuoteResponseModel>(instance);
        }

        /// <summary>
        /// Test the property 'QuotesValidFrom'
        /// </summary>
        [Fact]
        public void QuotesValidFromTest()
        {
            // TODO unit test for the property 'QuotesValidFrom'
        }

        /// <summary>
        /// Test the property 'TotalQuotes'
        /// </summary>
        [Fact]
        public void TotalQuotesTest()
        {
            // TODO unit test for the property 'TotalQuotes'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'Quotes'
        /// </summary>
        [Fact]
        public void QuotesTest()
        {
            // TODO unit test for the property 'Quotes'
        }
    }
}
