/*
 * Norsk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: helpdesk@norsk-global.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DA.Systems.Cube.Norsk.Model;
using DA.Systems.Cube.Norsk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DA.Systems.Cube.Norsk.Test.Model
{
    /// <summary>
    ///  Class for testing QuoteRequestModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QuoteRequestModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QuoteRequestModel
        //private QuoteRequestModel instance;

        public QuoteRequestModelTests()
        {
            // TODO uncomment below to create an instance of QuoteRequestModel
            //instance = new QuoteRequestModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QuoteRequestModel
        /// </summary>
        [Fact]
        public void QuoteRequestModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" QuoteRequestModel
            //Assert.IsType<QuoteRequestModel>(instance);
        }

        /// <summary>
        /// Test the property 'ShippingDate'
        /// </summary>
        [Fact]
        public void ShippingDateTest()
        {
            // TODO unit test for the property 'ShippingDate'
        }

        /// <summary>
        /// Test the property 'Zipcode'
        /// </summary>
        [Fact]
        public void ZipcodeTest()
        {
            // TODO unit test for the property 'Zipcode'
        }

        /// <summary>
        /// Test the property 'Town'
        /// </summary>
        [Fact]
        public void TownTest()
        {
            // TODO unit test for the property 'Town'
        }

        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Fact]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }

        /// <summary>
        /// Test the property 'Collection'
        /// </summary>
        [Fact]
        public void CollectionTest()
        {
            // TODO unit test for the property 'Collection'
        }

        /// <summary>
        /// Test the property 'Dutiable'
        /// </summary>
        [Fact]
        public void DutiableTest()
        {
            // TODO unit test for the property 'Dutiable'
        }

        /// <summary>
        /// Test the property 'AdditionalServiceOptions'
        /// </summary>
        [Fact]
        public void AdditionalServiceOptionsTest()
        {
            // TODO unit test for the property 'AdditionalServiceOptions'
        }

        /// <summary>
        /// Test the property 'Pieces'
        /// </summary>
        [Fact]
        public void PiecesTest()
        {
            // TODO unit test for the property 'Pieces'
        }

        /// <summary>
        /// Test the property 'Specials'
        /// </summary>
        [Fact]
        public void SpecialsTest()
        {
            // TODO unit test for the property 'Specials'
        }
    }
}
