/*
 * Norsk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: helpdesk@norsk-global.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DA.Systems.Cube.Norsk.Model;
using DA.Systems.Cube.Norsk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DA.Systems.Cube.Norsk.Test.Model
{
    /// <summary>
    ///  Class for testing RequestField
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RequestFieldTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RequestField
        //private RequestField instance;

        public RequestFieldTests()
        {
            // TODO uncomment below to create an instance of RequestField
            //instance = new RequestField();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RequestField
        /// </summary>
        [Fact]
        public void RequestFieldInstanceTest()
        {
            // TODO uncomment below to test "IsType" RequestField
            //Assert.IsType<RequestField>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
    }
}
