/*
 * Norsk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: helpdesk@norsk-global.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DA.Systems.Cube.Norsk.Model;
using DA.Systems.Cube.Norsk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DA.Systems.Cube.Norsk.Test.Model
{
    /// <summary>
    ///  Class for testing ShipmentArchiveDocument
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ShipmentArchiveDocumentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ShipmentArchiveDocument
        //private ShipmentArchiveDocument instance;

        public ShipmentArchiveDocumentTests()
        {
            // TODO uncomment below to create an instance of ShipmentArchiveDocument
            //instance = new ShipmentArchiveDocument();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ShipmentArchiveDocument
        /// </summary>
        [Fact]
        public void ShipmentArchiveDocumentInstanceTest()
        {
            // TODO uncomment below to test "IsType" ShipmentArchiveDocument
            //Assert.IsType<ShipmentArchiveDocument>(instance);
        }

        /// <summary>
        /// Test the property 'Contents'
        /// </summary>
        [Fact]
        public void ContentsTest()
        {
            // TODO unit test for the property 'Contents'
        }
    }
}
