/*
 * Norsk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: helpdesk@norsk-global.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DA.Systems.Cube.Norsk.Model;
using DA.Systems.Cube.Norsk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DA.Systems.Cube.Norsk.Test.Model
{
    /// <summary>
    ///  Class for testing ShipmentBookingResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ShipmentBookingResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ShipmentBookingResponse
        //private ShipmentBookingResponse instance;

        public ShipmentBookingResponseTests()
        {
            // TODO uncomment below to create an instance of ShipmentBookingResponse
            //instance = new ShipmentBookingResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ShipmentBookingResponse
        /// </summary>
        [Fact]
        public void ShipmentBookingResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ShipmentBookingResponse
            //Assert.IsType<ShipmentBookingResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Barcode'
        /// </summary>
        [Fact]
        public void BarcodeTest()
        {
            // TODO unit test for the property 'Barcode'
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'NorskBarcode'
        /// </summary>
        [Fact]
        public void NorskBarcodeTest()
        {
            // TODO unit test for the property 'NorskBarcode'
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

        /// <summary>
        /// Test the property 'ArchiveDocuments'
        /// </summary>
        [Fact]
        public void ArchiveDocumentsTest()
        {
            // TODO unit test for the property 'ArchiveDocuments'
        }

        /// <summary>
        /// Test the property 'CollectionReferenceNumber'
        /// </summary>
        [Fact]
        public void CollectionReferenceNumberTest()
        {
            // TODO unit test for the property 'CollectionReferenceNumber'
        }

        /// <summary>
        /// Test the property 'CollectionDateTime'
        /// </summary>
        [Fact]
        public void CollectionDateTimeTest()
        {
            // TODO unit test for the property 'CollectionDateTime'
        }
    }
}
