/*
 * Norsk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: helpdesk@norsk-global.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DA.Systems.Cube.Norsk.Model;
using DA.Systems.Cube.Norsk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DA.Systems.Cube.Norsk.Test.Model
{
    /// <summary>
    ///  Class for testing ShipmentBookingRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ShipmentBookingRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ShipmentBookingRequest
        //private ShipmentBookingRequest instance;

        public ShipmentBookingRequestTests()
        {
            // TODO uncomment below to create an instance of ShipmentBookingRequest
            //instance = new ShipmentBookingRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ShipmentBookingRequest
        /// </summary>
        [Fact]
        public void ShipmentBookingRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ShipmentBookingRequest
            //Assert.IsType<ShipmentBookingRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Pieces'
        /// </summary>
        [Fact]
        public void PiecesTest()
        {
            // TODO unit test for the property 'Pieces'
        }

        /// <summary>
        /// Test the property 'ReadyByDate'
        /// </summary>
        [Fact]
        public void ReadyByDateTest()
        {
            // TODO unit test for the property 'ReadyByDate'
        }

        /// <summary>
        /// Test the property 'Hawb'
        /// </summary>
        [Fact]
        public void HawbTest()
        {
            // TODO unit test for the property 'Hawb'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'NonDox'
        /// </summary>
        [Fact]
        public void NonDoxTest()
        {
            // TODO unit test for the property 'NonDox'
        }

        /// <summary>
        /// Test the property 'DDP'
        /// </summary>
        [Fact]
        public void DDPTest()
        {
            // TODO unit test for the property 'DDP'
        }

        /// <summary>
        /// Test the property 'Pallet'
        /// </summary>
        [Fact]
        public void PalletTest()
        {
            // TODO unit test for the property 'Pallet'
        }

        /// <summary>
        /// Test the property 'Invoice'
        /// </summary>
        [Fact]
        public void InvoiceTest()
        {
            // TODO unit test for the property 'Invoice'
        }

        /// <summary>
        /// Test the property 'Requestor'
        /// </summary>
        [Fact]
        public void RequestorTest()
        {
            // TODO unit test for the property 'Requestor'
        }

        /// <summary>
        /// Test the property 'Consignee'
        /// </summary>
        [Fact]
        public void ConsigneeTest()
        {
            // TODO unit test for the property 'Consignee'
        }

        /// <summary>
        /// Test the property 'Collection'
        /// </summary>
        [Fact]
        public void CollectionTest()
        {
            // TODO unit test for the property 'Collection'
        }

        /// <summary>
        /// Test the property 'Shipper'
        /// </summary>
        [Fact]
        public void ShipperTest()
        {
            // TODO unit test for the property 'Shipper'
        }

        /// <summary>
        /// Test the property 'Service'
        /// </summary>
        [Fact]
        public void ServiceTest()
        {
            // TODO unit test for the property 'Service'
        }

        /// <summary>
        /// Test the property 'Specials'
        /// </summary>
        [Fact]
        public void SpecialsTest()
        {
            // TODO unit test for the property 'Specials'
        }

        /// <summary>
        /// Test the property 'Picking'
        /// </summary>
        [Fact]
        public void PickingTest()
        {
            // TODO unit test for the property 'Picking'
        }

        /// <summary>
        /// Test the property 'LabelFormat'
        /// </summary>
        [Fact]
        public void LabelFormatTest()
        {
            // TODO unit test for the property 'LabelFormat'
        }

        /// <summary>
        /// Test the property 'Site'
        /// </summary>
        [Fact]
        public void SiteTest()
        {
            // TODO unit test for the property 'Site'
        }

        /// <summary>
        /// Test the property 'ExportCustoms'
        /// </summary>
        [Fact]
        public void ExportCustomsTest()
        {
            // TODO unit test for the property 'ExportCustoms'
        }

        /// <summary>
        /// Test the property 'CustomDeclarations'
        /// </summary>
        [Fact]
        public void CustomDeclarationsTest()
        {
            // TODO unit test for the property 'CustomDeclarations'
        }

        /// <summary>
        /// Test the property 'LabelSize'
        /// </summary>
        [Fact]
        public void LabelSizeTest()
        {
            // TODO unit test for the property 'LabelSize'
        }
    }
}
