/*
 * Norsk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: helpdesk@norsk-global.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DA.Systems.Cube.Norsk.Model;
using DA.Systems.Cube.Norsk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DA.Systems.Cube.Norsk.Test.Model
{
    /// <summary>
    ///  Class for testing ShipmentBookingItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ShipmentBookingItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ShipmentBookingItem
        //private ShipmentBookingItem instance;

        public ShipmentBookingItemTests()
        {
            // TODO uncomment below to create an instance of ShipmentBookingItem
            //instance = new ShipmentBookingItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ShipmentBookingItem
        /// </summary>
        [Fact]
        public void ShipmentBookingItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" ShipmentBookingItem
            //Assert.IsType<ShipmentBookingItem>(instance);
        }

        /// <summary>
        /// Test the property 'NorskBarcode'
        /// </summary>
        [Fact]
        public void NorskBarcodeTest()
        {
            // TODO unit test for the property 'NorskBarcode'
        }

        /// <summary>
        /// Test the property 'Barcode'
        /// </summary>
        [Fact]
        public void BarcodeTest()
        {
            // TODO unit test for the property 'Barcode'
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'ScanBarcode'
        /// </summary>
        [Fact]
        public void ScanBarcodeTest()
        {
            // TODO unit test for the property 'ScanBarcode'
        }

        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Fact]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }
    }
}
