/*
 * Norsk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: helpdesk@norsk-global.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DA.Systems.Cube.Norsk.Model;
using DA.Systems.Cube.Norsk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DA.Systems.Cube.Norsk.Test.Model
{
    /// <summary>
    ///  Class for testing TypeOfExport
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TypeOfExportTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TypeOfExport
        //private TypeOfExport instance;

        public TypeOfExportTests()
        {
            // TODO uncomment below to create an instance of TypeOfExport
            //instance = new TypeOfExport();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TypeOfExport
        /// </summary>
        [Fact]
        public void TypeOfExportInstanceTest()
        {
            // TODO uncomment below to test "IsType" TypeOfExport
            //Assert.IsType<TypeOfExport>(instance);
        }
    }
}
