/*
 * Norsk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: helpdesk@norsk-global.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DA.Systems.Cube.Norsk.Model;
using DA.Systems.Cube.Norsk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DA.Systems.Cube.Norsk.Test.Model
{
    /// <summary>
    ///  Class for testing ValidationErrors
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ValidationErrorsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ValidationErrors
        //private ValidationErrors instance;

        public ValidationErrorsTests()
        {
            // TODO uncomment below to create an instance of ValidationErrors
            //instance = new ValidationErrors();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ValidationErrors
        /// </summary>
        [Fact]
        public void ValidationErrorsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ValidationErrors
            //Assert.IsType<ValidationErrors>(instance);
        }

        /// <summary>
        /// Test the property 'TargetSite'
        /// </summary>
        [Fact]
        public void TargetSiteTest()
        {
            // TODO unit test for the property 'TargetSite'
        }

        /// <summary>
        /// Test the property 'StackTrace'
        /// </summary>
        [Fact]
        public void StackTraceTest()
        {
            // TODO unit test for the property 'StackTrace'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'InnerException'
        /// </summary>
        [Fact]
        public void InnerExceptionTest()
        {
            // TODO unit test for the property 'InnerException'
        }

        /// <summary>
        /// Test the property 'HelpLink'
        /// </summary>
        [Fact]
        public void HelpLinkTest()
        {
            // TODO unit test for the property 'HelpLink'
        }

        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }

        /// <summary>
        /// Test the property 'HResult'
        /// </summary>
        [Fact]
        public void HResultTest()
        {
            // TODO unit test for the property 'HResult'
        }

        /// <summary>
        /// Test the property 'ErrorCode'
        /// </summary>
        [Fact]
        public void ErrorCodeTest()
        {
            // TODO unit test for the property 'ErrorCode'
        }

        /// <summary>
        /// Test the property 'Fields'
        /// </summary>
        [Fact]
        public void FieldsTest()
        {
            // TODO unit test for the property 'Fields'
        }

        /// <summary>
        /// Test the property 'PublicMessage'
        /// </summary>
        [Fact]
        public void PublicMessageTest()
        {
            // TODO unit test for the property 'PublicMessage'
        }
    }
}
