/*
 * Norsk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: helpdesk@norsk-global.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = DA.Systems.Cube.Norsk.Client.FileParameter;
using OpenAPIDateConverter = DA.Systems.Cube.Norsk.Client.OpenAPIDateConverter;

namespace DA.Systems.Cube.Norsk.Model
{
    /// <summary>
    /// Defines DangerousGoods
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DangerousGoods
    {
        /// <summary>
        /// Enum DI for value: DI
        /// </summary>
        [EnumMember(Value = "DI")]
        DI = 1,

        /// <summary>
        /// Enum BS for value: BS
        /// </summary>
        [EnumMember(Value = "BS")]
        BS = 2,

        /// <summary>
        /// Enum BSDI for value: BSDI
        /// </summary>
        [EnumMember(Value = "BSDI")]
        BSDI = 3,

        /// <summary>
        /// Enum ID8000 for value: ID8000
        /// </summary>
        [EnumMember(Value = "ID8000")]
        ID8000 = 4,

        /// <summary>
        /// Enum BCB for value: BCB
        /// </summary>
        [EnumMember(Value = "BCB")]
        BCB = 5,

        /// <summary>
        /// Enum FULL for value: FULL
        /// </summary>
        [EnumMember(Value = "FULL")]
        FULL = 6,

        /// <summary>
        /// Enum LIBP1 for value: LIBP1
        /// </summary>
        [EnumMember(Value = "LIBP1")]
        LIBP1 = 7,

        /// <summary>
        /// Enum LIBP2 for value: LIBP2
        /// </summary>
        [EnumMember(Value = "LIBP2")]
        LIBP2 = 8,

        /// <summary>
        /// Enum LMBP1 for value: LMBP1
        /// </summary>
        [EnumMember(Value = "LMBP1")]
        LMBP1 = 9,

        /// <summary>
        /// Enum LMBP2 for value: LMBP2
        /// </summary>
        [EnumMember(Value = "LMBP2")]
        LMBP2 = 10,

        /// <summary>
        /// Enum LMBP1969 for value: LMBP1969
        /// </summary>
        [EnumMember(Value = "LMBP1969")]
        LMBP1969 = 11,

        /// <summary>
        /// Enum LMBP1970 for value: LMBP1970
        /// </summary>
        [EnumMember(Value = "LMBP1970")]
        LMBP1970 = 12,

        /// <summary>
        /// Enum DGLB for value: DGLB
        /// </summary>
        [EnumMember(Value = "DGLB")]
        DGLB = 13
    }

}
