/*
 * Norsk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: helpdesk@norsk-global.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = DA.Systems.Cube.Norsk.Client.FileParameter;
using OpenAPIDateConverter = DA.Systems.Cube.Norsk.Client.OpenAPIDateConverter;

namespace DA.Systems.Cube.Norsk.Model
{
    /// <summary>
    /// Defines LabelSize
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LabelSize
    {
        /// <summary>
        /// Enum A4 for value: A4
        /// </summary>
        [EnumMember(Value = "A4")]
        A4 = 1,

        /// <summary>
        /// Enum FourBySix for value: FourBySix
        /// </summary>
        [EnumMember(Value = "FourBySix")]
        FourBySix = 2,

        /// <summary>
        /// Enum FourByEight for value: FourByEight
        /// </summary>
        [EnumMember(Value = "FourByEight")]
        FourByEight = 3
    }

}
