/*
 * Norsk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: helpdesk@norsk-global.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = DA.Systems.Cube.Norsk.Client.FileParameter;
using OpenAPIDateConverter = DA.Systems.Cube.Norsk.Client.OpenAPIDateConverter;

namespace DA.Systems.Cube.Norsk.Model
{
    /// <summary>
    /// ProofOfDelivery
    /// </summary>
    [DataContract(Name = "ProofOfDelivery")]
    public class ProofOfDelivery : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProofOfDelivery" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public ProofOfDelivery()
        {
        }

        /// <summary>
        /// Gets or Sets SignedOn
        /// </summary>
        [DataMember(Name = "SignedOn", EmitDefaultValue = true)]
        public DateTimeOffset? SignedOn { get; private set; }

        /// <summary>
        /// Returns false as SignedOn should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeSignedOn()
        {
            return false;
        }
        /// <summary>
        /// Gets or Sets SignedBy
        /// </summary>
        [DataMember(Name = "SignedBy", EmitDefaultValue = true)]
        public string SignedBy { get; private set; }

        /// <summary>
        /// Returns false as SignedBy should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeSignedBy()
        {
            return false;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProofOfDelivery {\n");
            sb.Append("  SignedOn: ").Append(SignedOn).Append("\n");
            sb.Append("  SignedBy: ").Append(SignedBy).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
