/*
 * Norsk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: helpdesk@norsk-global.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = DA.Systems.Cube.Norsk.Client.FileParameter;
using OpenAPIDateConverter = DA.Systems.Cube.Norsk.Client.OpenAPIDateConverter;

namespace DA.Systems.Cube.Norsk.Model
{
    /// <summary>
    /// Represents a piece in the shipment. This class provides specific details about a piece&#39;s dimensions (length, width, height), weight, and the quantity of such pieces in a shipment.
    /// </summary>
    [DataContract(Name = "QuoteRequestPiece")]
    public class QuoteRequestPiece : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QuoteRequestPiece" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected QuoteRequestPiece() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="QuoteRequestPiece" /> class.
        /// </summary>
        /// <param name="length">The length dimension of the shipment piece..</param>
        /// <param name="width">The width dimension of the shipment piece..</param>
        /// <param name="height">The height dimension of the shipment piece..</param>
        /// <param name="weight">The weight of the shipment piece. (required).</param>
        /// <param name="numberOfPieces">The quantity of pieces. (required).</param>
        public QuoteRequestPiece(double length = default(double), double width = default(double), double height = default(double), double weight = default(double), int numberOfPieces = default(int))
        {
            Weight = weight;
            NumberOfPieces = numberOfPieces;
            Length = length;
            Width = width;
            Height = height;
        }

        /// <summary>
        /// The length dimension of the shipment piece.
        /// </summary>
        /// <value>The length dimension of the shipment piece.</value>
        [DataMember(Name = "Length", EmitDefaultValue = true)]
        public double Length { get; set; }

        /// <summary>
        /// The width dimension of the shipment piece.
        /// </summary>
        /// <value>The width dimension of the shipment piece.</value>
        [DataMember(Name = "Width", EmitDefaultValue = true)]
        public double Width { get; set; }

        /// <summary>
        /// The height dimension of the shipment piece.
        /// </summary>
        /// <value>The height dimension of the shipment piece.</value>
        [DataMember(Name = "Height", EmitDefaultValue = true)]
        public double Height { get; set; }

        /// <summary>
        /// The weight of the shipment piece.
        /// </summary>
        /// <value>The weight of the shipment piece.</value>
        [DataMember(Name = "Weight", IsRequired = true, EmitDefaultValue = true)]
        public double Weight { get; set; }

        /// <summary>
        /// The quantity of pieces.
        /// </summary>
        /// <value>The quantity of pieces.</value>
        [DataMember(Name = "NumberOfPieces", IsRequired = true, EmitDefaultValue = true)]
        public int NumberOfPieces { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QuoteRequestPiece {\n");
            sb.Append("  Length: ").Append(Length).Append("\n");
            sb.Append("  Width: ").Append(Width).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  Weight: ").Append(Weight).Append("\n");
            sb.Append("  NumberOfPieces: ").Append(NumberOfPieces).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Weight (double) minimum
            if (Weight < (double)0)
            {
                yield return new ValidationResult("Invalid value for Weight, must be a value greater than or equal to 0.", new [] { "Weight" });
            }

            // NumberOfPieces (int) minimum
            if (NumberOfPieces < (int)0)
            {
                yield return new ValidationResult("Invalid value for NumberOfPieces, must be a value greater than or equal to 0.", new [] { "NumberOfPieces" });
            }

            yield break;
        }
    }

}
