/*
 * Norsk API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: helpdesk@norsk-global.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = DA.Systems.Cube.Norsk.Client.FileParameter;
using OpenAPIDateConverter = DA.Systems.Cube.Norsk.Client.OpenAPIDateConverter;

namespace DA.Systems.Cube.Norsk.Model
{
    /// <summary>
    /// QuoteCost
    /// </summary>
    [DataContract(Name = "QuoteCost")]
    public class QuoteCost : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QuoteCost" /> class.
        /// </summary>
        /// <param name="reference">reference.</param>
        /// <param name="baseCost">baseCost.</param>
        /// <param name="fuelCost">fuelCost.</param>
        public QuoteCost(string reference = default(string), double baseCost = default(double), double? fuelCost = default(double?))
        {
            Reference = reference;
            BaseCost = baseCost;
            FuelCost = fuelCost;
        }

        /// <summary>
        /// Gets or Sets Reference
        /// </summary>
        [DataMember(Name = "Reference", EmitDefaultValue = true)]
        public string Reference { get; set; }

        /// <summary>
        /// Gets or Sets BaseCost
        /// </summary>
        [DataMember(Name = "BaseCost", EmitDefaultValue = true)]
        public double BaseCost { get; set; }

        /// <summary>
        /// Gets or Sets FuelCost
        /// </summary>
        [DataMember(Name = "FuelCost", EmitDefaultValue = true)]
        public double? FuelCost { get; set; }

        /// <summary>
        /// Gets or Sets TotalCost
        /// </summary>
        [DataMember(Name = "TotalCost", EmitDefaultValue = true)]
        public double TotalCost { get; private set; }

        /// <summary>
        /// Returns false as TotalCost should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeTotalCost()
        {
            return false;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QuoteCost {\n");
            sb.Append("  Reference: ").Append(Reference).Append("\n");
            sb.Append("  BaseCost: ").Append(BaseCost).Append("\n");
            sb.Append("  FuelCost: ").Append(FuelCost).Append("\n");
            sb.Append("  TotalCost: ").Append(TotalCost).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
