/*
 * MITA Notifications Platform REST API
 *
 * The Notifications REST API allows programmatic access to the Notifications Portal message funtionality. To use the REST API, you will need a Notifications Portal Account and an API key and secret. You can generate from the Notifications Portal using the API Key Manager.The REST API takes full advantage of all HTTP headers. Each part of a request and response is meaningful, including the request method (GET/POST, etc.), the individual headers (Location, Content-Type, Accept, etc.), and the response status code (200, 400, 404, etc.). Use of this API assumes a working knowledge of these HTTP components, and general use of RESTful web APIs.
 *
 * The version of the OpenAPI document: v1
 * Contact: notifications.mita@gov.mt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Mita.Notifications.Client.Client.OpenAPIDateConverter;

namespace Mita.Notifications.Client.Model;

/// <summary>
/// Defines Salutation
/// </summary>
[JsonConverter(typeof(StringEnumConverter))]
public enum Salutation
{
    /// <summary>
    /// Enum Mr for value: Mr
    /// </summary>
    [EnumMember(Value = "Mr")]
    Mr = 1,

    /// <summary>
    /// Enum Miss for value: Miss
    /// </summary>
    [EnumMember(Value = "Miss")]
    Miss = 2,

    /// <summary>
    /// Enum Mrs for value: Mrs
    /// </summary>
    [EnumMember(Value = "Mrs")]
    Mrs = 3,

    /// <summary>
    /// Enum Ms for value: Ms
    /// </summary>
    [EnumMember(Value = "Ms")]
    Ms = 4,

    /// <summary>
    /// Enum Dr for value: Dr
    /// </summary>
    [EnumMember(Value = "Dr")]
    Dr = 5,

    /// <summary>
    /// Enum Prof for value: Prof
    /// </summary>
    [EnumMember(Value = "Prof")]
    Prof = 6
}